{
 "title": "DCU Exporter",
 "description": "Dashboard to visualize DCU metrics using Prometheus Data Source via dcu_exporter job",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "node:",
    "query": {
     "query": "label_values(dcu_utilizationrate,node)"
    }
   },
   {
    "name": "dcu_id",
    "label": "dcu_id:",
    "query": {
     "query": "label_values(dcu_utilizationrate,minor_number)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "DCU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(dcu_utilizationrate{node=~\"$node\", minor_number=~\"$dcu_id\"}) without(container,dcu_pod_name,dcu_pod_namespace)",
     "legendFormat": "node=\"{{node}}\",name=\"{{name}}\",dcu_id= \"{{minor_number}}\",device_id=\"{{device_id}}\",pcieBus_number=\"{{pcieBus_number}}\""
    }
   ]
  },
  {
   "title": "DCU Avg. Utilization",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(dcu_utilizationrate{node=~\"$node\", minor_number=~\"$dcu_id\"})"
    }
   ]
  },
  {
   "title": "DCU Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(100*dcu_usedmemory_bytes/dcu_memorycap_bytes{node=~\"$node\", minor_number=~\"$dcu_id\"}) without(container,dcu_pod_name,dcu_pod_namespace)",
     "legendFormat": "node=\"{{node}}\",name=\"{{name}}\",dcu_id= \"{{minor_number}}\",device_id=\"{{device_id}}\",pcieBus_number=\"{{pcieBus_number}}\""
    }
   ]
  },
  {
   "title": "DCU Mem Total Used",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dcu_usedmemory_bytes{node=~\"$node\", minor_number=~\"$dcu_id\"})"
    }
   ]
  },
  {
   "title": "DCU Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg(dcu_power_usage{node=~\"$node\", minor_number=~\"$dcu_id\"}) without(container,dcu_pod_name,dcu_pod_namespace)",
     "legendFormat": "node=\"{{node}}\",name=\"{{name}}\",dcu_id= \"{{minor_number}}\",device_id=\"{{device_id}}\",pcieBus_number=\"{{pcieBus_number}}\""
    }
   ]
  },
  {
   "title": "DCU Total Power",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dcu_power_usage{node=~\"$node\", minor_number=~\"$dcu_id\"})"
    }
   ]
  },
  {
   "title": "DCU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(dcu_temp{node=~\"$node\", minor_number=~\"$dcu_id\"}) without(container,dcu_pod_name,dcu_pod_namespace)",
     "legendFormat": "node=\"{{node}}\",name=\"{{name}}\",dcu_id= \"{{minor_number}}\",device_id=\"{{device_id}}\",pcieBus_number=\"{{pcieBus_number}}\""
    }
   ]
  },
  {
   "title": "DCU Avg. Temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(dcu_temp{node=~\"$node\", minor_number=~\"$dcu_id\"})"
    }
   ]
  },
  {
   "title": "DCU PCIe Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "avg(dcu_pciebw_mb{node=~\"$node\", minor_number=~\"$dcu_id\"}) without(container,dcu_pod_name,dcu_pod_namespace)",
     "legendFormat": "node=\"{{node}}\",name=\"{{name}}\",dcu_id= \"{{minor_number}}\",device_id=\"{{device_id}}\",pcieBus_number=\"{{pcieBus_number}}\""
    }
   ]
  },
  {
   "title": "DCU Total CE Count",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dcu_ce_count{node=~\"$node\", minor_number=~\"$dcu_id\"})"
    }
   ]
  },
  {
   "title": "DCU Sclk",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "targets": [
    {
     "expr": "avg(dcu_sclk{node=~\"$node\", minor_number=~\"$dcu_id\"}) without(container,dcu_pod_name,dcu_pod_namespace)",
     "legendFormat": "node=\"{{node}}\",name=\"{{name}}\",dcu_id= \"{{minor_number}}\",device_id=\"{{device_id}}\",pcieBus_number=\"{{pcieBus_number}}\""
    }
   ]
  },
  {
   "title": "DCU Total UE Count",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dcu_ue_count{node=~\"$node\", minor_number=~\"$dcu_id\"})"
    }
   ]
  },
  {
   "title": "DCU CE Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg without(container, dcu_pod_name, dcu_pod_namespace) (dcu_ce_count{node=~\"$node\", minor_number=~\"$dcu_id\"})",
     "legendFormat": "node=\"{{node}}\",name=\"{{name}}\",dcu_id= \"{{minor_number}}\",device_id=\"{{device_id}}\",pcieBus_number=\"{{pcieBus_number}}\",block_type=\"{{block_type}}\""
    }
   ]
  },
  {
   "title": "DCU UE Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg without(container, dcu_pod_name, dcu_pod_namespace) (dcu_ue_count{node=~\"$node\", minor_number=~\"$dcu_id\"})",
     "legendFormat": "node=\"{{node}}\",name=\"{{name}}\",dcu_id= \"{{minor_number}}\",device_id=\"{{device_id}}\",pcieBus_number=\"{{pcieBus_number}}\",block_type=\"{{block_type}}\""
    }
   ]
  },
  {
   "title": "VDCU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg without(container, dcu_pod_name, dcu_pod_namespace) (vdcu_utilizationrate{node=~\"$node\", minor_number=~\"$dcu_id\"})",
     "legendFormat": "node=\"{{node}}\",name=\"{{name}}\",dcu_id= \"{{minor_number}}\",device_id=\"{{device_id}}\",vdcu_computer_unit=\"{{vdcu_computer_unit}}\",vdcu_memory_cap=\"{{vdcu_memory_cap}}\",vdcu_minor_number=\"{{vdcu_minor_number}}\""
    }
   ]
  },
  {
   "title": "VDCU Used Memory Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg without(container, dcu_pod_name, dcu_pod_namespace) (vdcu_usedmemory_bytes{node=~\"$node\", minor_number=~\"$dcu_id\"})",
     "legendFormat": "node=\"{{node}}\",name=\"{{name}}\",dcu_id= \"{{minor_number}}\",device_id=\"{{device_id}}\",vdcu_computer_unit=\"{{vdcu_computer_unit}}\",vdcu_memory_cap=\"{{vdcu_memory_cap}}\",vdcu_minor_number=\"{{vdcu_minor_number}}\""
    }
   ]
  }
 ]
}