{
 "title": "KUNLUN DCXM Exporter Dashboard",
 "description": "This dashboard is to display the metrics from DCXM Exporter",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(DCGM_FI_DEV_GPU_TEMP, instance)"
   },
   { "name": "gpu", "query": "label_values(gpu)" }
  ]
 },
 "panels": [
  {
   "title": "XPU Avg. Temp",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_TEMP{instance=~\"${instance}\", gpu=~\"${gpu}\"})"
    }
   ]
  },
  {
   "title": "XPU Power Total",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_POWER_USAGE{instance=~\"${instance}\", gpu=~\"${gpu}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "XPU Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{instance=~\"${instance}\", gpu=~\"${gpu}\"}",
     "legendFormat": "XPU {{gpu}}"
    }
   ]
  },
  {
   "title": "XPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{instance=~\"${instance}\", gpu=~\"${gpu}\"}",
     "legendFormat": "XPU {{gpu}}"
    }
   ]
  },
  {
   "title": "XPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{instance=~\"${instance}\", gpu=~\"${gpu}\"}",
     "legendFormat": "XPU {{gpu}}"
    }
   ]
  },
  {
   "title": "XPU Framebuffer Mem Used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{instance=~\"${instance}\", gpu=~\"${gpu}\"}",
     "legendFormat": "XPU {{gpu}}"
    }
   ]
  },
  {
   "title": "XPU Last XID",
   "type": "stat",
   "description": "Value of the last XID error encountered.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_XID_ERRORS{instance=~\"${instance}\", gpu=~\"${gpu}\"}",
     "legendFormat": "XPU {{gpu}}"
    }
   ]
  },
  {
   "title": "XPU Volatile SBE",
   "type": "stat",
   "description": "Total number of single-bit volatile ECC errors.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_ECC_SBE_VOL_TOTAL{instance=~\"${instance}\", gpu=~\"${gpu}\"}",
     "legendFormat": "XPU {{gpu}}"
    }
   ]
  },
  {
   "title": "XPU Volatile DBE",
   "type": "stat",
   "description": "Total number of double-bit volatile ECC errors.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_ECC_DBE_VOL_TOTAL{instance=~\"${instance}\", gpu=~\"${gpu}\"}",
     "legendFormat": "XPU {{gpu}}"
    }
   ]
  },
  {
   "title": "XPU Persistent SBE",
   "type": "stat",
   "description": "Total number of single-bit persistent ECC errors.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_ECC_SBE_AGG_TOTAL{instance=~\"${instance}\", gpu=~\"${gpu}\"}",
     "legendFormat": "XPU {{gpu}}"
    }
   ]
  },
  {
   "title": "XPU Persistent DBE",
   "type": "stat",
   "description": "Total number of double-bit persistent ECC errors.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_ECC_DBE_AGG_TOTAL{instance=~\"${instance}\", gpu=~\"${gpu}\"}",
     "legendFormat": "XPU {{gpu}}"
    }
   ]
  }
 ]
}