apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: minio
    meta.helm.sh/release-namespace: minio
  labels:
    app.kubernetes.io/managed-by: Helm
  name: minio
  namespace: minio
