apiVersion: v1
data:
  accesskey: QUtJQUlPU0ZPRE5ON0VYQU1QTEU=
  secretkey: d0phbHJYVXRuRkVNSS9LN01ERU5HL2JQeFJmaUNZRVhBTVBMRUtFWQ==
kind: Secret
metadata:
  annotations:
    field.cattle.io/projectId: local:p-58jwj
    meta.helm.sh/release-name: minio
    meta.helm.sh/release-namespace: minio
  labels:
    app: minio
    app.kubernetes.io/managed-by: Helm
    chart: minio-5.0.19
    heritage: Helm
    release: minio
  name: minio
  namespace: minio
